name: Manage Pull Requests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'khanabid20' || 
        github.actor == 'abid'
    
    steps:
    - run: echo Hello, world!
